In [1]:
import pandas as pd

In [2]:
pd.read_csv("D:\Data\Drive_D\TRAINING data sets\TechCrunchcontinentalUSA.csv")

,permalink,company,numEmps,category,city,state,fundedDate,raisedAmt,raisedCurrency,round123
0,lifelock,LifeLock,NaN,web,Tempe,AZ,1-May-07,6850000.0,USD,b
1,lifelock,LifeLock,NaN,web,Tempe,AZ,1-Oct-06,6000000.0,USD,a
2,lifelock,LifeLock,NaN,web,Tempe,AZ,1-Jan-08,25000000.0,USD,c
3,mycityfaces,MyCityFaces,7.0,web,Scottsdale,AZ,1-Jan-08,50000.0,USD,seed
4,flypaper,Flypaper,NaN,web,Phoenix,AZ,1-Feb-08,3000000.0,USD,a
5,infusionsoft,Infusionsoft,105.0,software,Gilbert,AZ,1-Oct-07,9000000.0,USD,a
6,gauto,gAuto,4.0,web,Scottsdale,AZ,1-Jan-08,250000.0,USD,seed
7,chosenlist-com,ChosenList.com,5.0,web,Scottsdale,AZ,1-Oct-06,140000.0,USD,seed
8,chosenlist-com,ChosenList.com,5.0,web,Scottsdale,AZ,25-Jan-08,233750.0,USD,angel
9,digg,Digg,60.0,web,San Francisco,CA,1-Dec-06,8500000.0,USD,b
10,digg,Digg,60.0,web,San Francisco,CA,1-Oct-05,2800000.0,USD,a
11,facebook,Facebook,450.0,web,Palo Alto,CA,1-Sep-04,500000.0,USD,angel
12,facebook,Facebook,450.0,web,Palo Alto,CA,1-May-05,12700000.0,USD,a
13,facebook,Facebook,450.0,web,Palo Alto,CA,1-Apr-06,27500000.0,USD,b
14,facebook,Facebook,450.0,web,Palo Alto,CA,1-Oct-07,300000000.0,USD,c
15,facebook,Facebook,450.0,web,Palo Alto,CA,1-Mar-08,40000000.0,USD,c
16,facebook,Facebook,450.0,web,Palo Alto,CA,15-Jan-08,15000000.0,USD,c
17,facebook,Facebook,450.0,web,Palo Alto,CA,1-May-08,100000000.0,USD,debt_round
18,photobucket,Photobucket,60.0,web,Palo Alto,CA,1-May-06,10500000.0,USD,b
19,photobucket,Photobucket,60.0,web,Palo Alto,CA,1-Mar-05,3000000.0,USD,a
20,omnidrive,Omnidrive,NaN,web,Palo Alto,CA,1-Dec-06,800000.0,USD,angel
21,geni,Geni,18.0,web,West Hollywood,CA,1-Jan-07,1500000.0,USD,a
22,geni,Geni,18.0,web,West Hollywood,CA,1-Mar-07,10000000.0,USD,b
23,twitter,Twitter,17.0,web,San Francisco,CA,1-Jul-07,5400000.0,USD,b
24,twitter,Twitter,17.0,web,San Francisco,CA,1-May-08,15000000.0,USD,c
25,stumbleupon,StumbleUpon,NaN,web,San Francisco,CA,1-Dec-05,1500000.0,USD,seed
26,gizmoz,Gizmoz,NaN,web,Menlo Park,CA,1-May-07,6300000.0,USD,a
27,gizmoz,Gizmoz,NaN,web,Menlo Park,CA,16-Mar-08,6500000.0,USD,b
28,scribd,Scribd,14.0,web,San Francisco,CA,1-Jun-06,12000.0,USD,seed
29,scribd,Scribd,14.0,web,San Francisco,CA,1-Jan-07,40000.0,USD,angel
...,...,...,...,...,...,...,...,...,...,...
1430,fyreball,Fyreball,NaN,web,Bellevue,WA,1-Dec-07,1000000.0,USD,angel
1431,delve-networks,Delve Networks,NaN,web,Seattle,WA,1-Dec-06,1650000.0,USD,seed
1432,delve-networks,Delve Networks,NaN,web,Seattle,WA,1-Aug-07,8000000.0,USD,a
1433,livemocha,LiveMocha,NaN,web,Bellevue,WA,1-Jan-08,6000000.0,USD,a
1434,mercentcorporation,Mercent Corporation,50.0,web,Seattle,WA,1-Jan-08,6500000.0,USD,b
1435,cleverset,CleverSet,NaN,web,Seattle,WA,1-Aug-06,1400000.0,USD,angel
1436,cleverset,CleverSet,NaN,web,Seattle,WA,1-Sep-05,1200000.0,USD,a
1437,cleverset,CleverSet,NaN,web,Seattle,WA,1-Dec-07,500000.0,USD,angel
1438,liquidplanner,LiquidPlanner,11.0,web,Bellevue,WA,1-Jan-08,1200000.0,USD,angel
1439,limeade,Limeade,10.0,web,Bellevue,WA,1-Jan-07,1000000.0,USD,angel
1440,yodio,Yodio,4.0,web,Bellevue,WA,1-Feb-08,850000.0,USD,a
1441,tastemakers,Tastemakers,11.0,web,Seattle,WA,1-Feb-07,1000000.0,USD,a
1442,whitepages-com,WhitePages.com,125.0,web,Seattle,WA,1-Aug-05,45000000.0,USD,a
1443,revenuescience,RevenueScience,NaN,web,Seattle,WA,19-Dec-05,24000000.0,USD,e
1444,gotvoice,GotVoice,15.0,mobile,Kirkland,WA,25-Oct-06,3000000.0,USD,a
1445,cardomain-network,CarDomain Network,50.0,web,Seattle,WA,29-Jun-07,3000000.0,USD,a
1446,mpire,mpire,NaN,web,Seattle,WA,1-Feb-07,9800000.0,USD,a
1447,mpire,mpire,NaN,web,Seattle,WA,11-Jun-08,10000000.0,USD,b
1448,teachstreet,TeachStreet,8.0,web,Seattle,WA,1-Mar-08,2250000.0,USD,a
1449,estately,Estately,NaN,web,NaN,WA,24-Apr-08,450000.0,USD,angel
1450,infinia,Infinia,NaN,cleantech,Kennewick,WA,22-Apr-08,57000000.0,USD,b
1451,infinia,Infinia,NaN,cleantech,Kennewick,WA,1-Jun-07,9500000.0,USD,a
1452,m-metrics,M:Metrics,NaN,web,Seattle,WA,16-Oct-05,7000000.0,USD,b
1453,cozi,Cozi,26.0,software,Seattle,WA,11-Jul-07,3000000.0,USD,a
1454,cozi,Cozi,26.0,software,Seattle,WA,1-Jun-08,8000000.0,USD,c
1455,trusera,Trusera,15.0,web,Seattle,WA,1-Jun-07,2000000.0,USD,angel
1456,alerts-com,Alerts.com,NaN,web,Bellevue,WA,8-Jul-08,1200000.0,USD,a
1457,myrio,Myrio,75.0,software,Bothell,WA,1-Jan-01,20500000.0,USD,unattributed
1458,grid-networks,Grid Networks,NaN,web,Seattle,WA,30-Oct-07,9500000.0,USD,a
1459,grid-networks,Grid Networks,NaN,web,Seattle,WA,20-May-08,10500000.0,USD,b

In [3]:
df=pd.read_csv("D:\Data\Drive_D\TRAINING data sets\TechCrunchcontinentalUSA.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 10 columns):
permalink         1460 non-null object
company           1456 non-null object
numEmps           567 non-null float64
category          1432 non-null object
city              1438 non-null object
state             1456 non-null object
fundedDate        1456 non-null object
raisedAmt         1456 non-null float64
raisedCurrency    1456 non-null object
round123          1456 non-null object
dtypes: float64(2), object(8)
memory usage: 68.5+ KB

In [5]:
df.permalink

0                 lifelock
1                 lifelock
2                 lifelock
3              mycityfaces
4                 flypaper
5             infusionsoft
6                    gauto
7           chosenlist-com
8           chosenlist-com
9                     digg
10                    digg
11                facebook
12                facebook
13                facebook
14                facebook
15                facebook
16                facebook
17                facebook
18             photobucket
19             photobucket
20               omnidrive
21                    geni
22                    geni
23                 twitter
24                 twitter
25             stumbleupon
26                  gizmoz
27                  gizmoz
28                  scribd
29                  scribd
               ...
1430              fyreball
1431        delve-networks
1432        delve-networks
1433             livemocha
1434    mercentcorporation
1435             cleverset
1436             cleverset
1437             cleverset
1438         liquidplanner
1439               limeade
1440                 yodio
1441           tastemakers
1442        whitepages-com
1443        revenuescience
1444              gotvoice
1445     cardomain-network
1446                 mpire
1447                 mpire
1448           teachstreet
1449              estately
1450               infinia
1451               infinia
1452             m-metrics
1453                  cozi
1454                  cozi
1455               trusera
1456            alerts-com
1457                 myrio
1458         grid-networks
1459         grid-networks
Name: permalink, Length: 1460, dtype: object

In [6]:
df.company

0                  LifeLock
1                  LifeLock
2                  LifeLock
3               MyCityFaces
4                  Flypaper
5              Infusionsoft
6                     gAuto
7            ChosenList.com
8            ChosenList.com
9                      Digg
10                     Digg
11                 Facebook
12                 Facebook
13                 Facebook
14                 Facebook
15                 Facebook
16                 Facebook
17                 Facebook
18              Photobucket
19              Photobucket
20                Omnidrive
21                     Geni
22                     Geni
23                  Twitter
24                  Twitter
25              StumbleUpon
26                   Gizmoz
27                   Gizmoz
28                   Scribd
29                   Scribd
               ...
1430               Fyreball
1431         Delve Networks
1432         Delve Networks
1433              LiveMocha
1434    Mercent Corporation
1435              CleverSet
1436              CleverSet
1437              CleverSet
1438          LiquidPlanner
1439                Limeade
1440                  Yodio
1441            Tastemakers
1442         WhitePages.com
1443         RevenueScience
1444               GotVoice
1445      CarDomain Network
1446                  mpire
1447                  mpire
1448            TeachStreet
1449               Estately
1450                Infinia
1451                Infinia
1452              M:Metrics
1453                   Cozi
1454                   Cozi
1455                Trusera
1456             Alerts.com
1457                  Myrio
1458          Grid Networks
1459          Grid Networks
Name: company, Length: 1460, dtype: object

In [7]:
df.round

<bound method DataFrame.round of                permalink              company  numEmps   category  \
0               lifelock             LifeLock      NaN        web
1               lifelock             LifeLock      NaN        web
2               lifelock             LifeLock      NaN        web
3            mycityfaces          MyCityFaces      7.0        web
4               flypaper             Flypaper      NaN        web
5           infusionsoft         Infusionsoft    105.0   software
6                  gauto                gAuto      4.0        web
7         chosenlist-com       ChosenList.com      5.0        web
8         chosenlist-com       ChosenList.com      5.0        web
9                   digg                 Digg     60.0        web
10                  digg                 Digg     60.0        web
11              facebook             Facebook    450.0        web
12              facebook             Facebook    450.0        web
13              facebook             Facebook    450.0        web
14              facebook             Facebook    450.0        web
15              facebook             Facebook    450.0        web
16              facebook             Facebook    450.0        web
17              facebook             Facebook    450.0        web
18           photobucket          Photobucket     60.0        web
19           photobucket          Photobucket     60.0        web
20             omnidrive            Omnidrive      NaN        web
21                  geni                 Geni     18.0        web
22                  geni                 Geni     18.0        web
23               twitter              Twitter     17.0        web
24               twitter              Twitter     17.0        web
25           stumbleupon          StumbleUpon      NaN        web
26                gizmoz               Gizmoz      NaN        web
27                gizmoz               Gizmoz      NaN        web
28                scribd               Scribd     14.0        web
29                scribd               Scribd     14.0        web
...                  ...                  ...      ...        ...
1430            fyreball             Fyreball      NaN        web
1431      delve-networks       Delve Networks      NaN        web
1432      delve-networks       Delve Networks      NaN        web
1433           livemocha            LiveMocha      NaN        web
1434  mercentcorporation  Mercent Corporation     50.0        web
1435           cleverset            CleverSet      NaN        web
1436           cleverset            CleverSet      NaN        web
1437           cleverset            CleverSet      NaN        web
1438       liquidplanner        LiquidPlanner     11.0        web
1439             limeade              Limeade     10.0        web
1440               yodio                Yodio      4.0        web
1441         tastemakers          Tastemakers     11.0        web
1442      whitepages-com       WhitePages.com    125.0        web
1443      revenuescience       RevenueScience      NaN        web
1444            gotvoice             GotVoice     15.0     mobile
1445   cardomain-network    CarDomain Network     50.0        web
1446               mpire                mpire      NaN        web
1447               mpire                mpire      NaN        web
1448         teachstreet          TeachStreet      8.0        web
1449            estately             Estately      NaN        web
1450             infinia              Infinia      NaN  cleantech
1451             infinia              Infinia      NaN  cleantech
1452           m-metrics            M:Metrics      NaN        web
1453                cozi                 Cozi     26.0   software
1454                cozi                 Cozi     26.0   software
1455             trusera              Trusera     15.0        web
1456          alerts-com           Alerts.com      NaN        web
1457               myrio                Myrio     75.0   software
1458       grid-networks        Grid Networks      NaN        web
1459       grid-networks        Grid Networks      NaN        web

                city state fundedDate    raisedAmt raisedCurrency  \
0              Tempe    AZ   1-May-07    6850000.0            USD
1              Tempe    AZ   1-Oct-06    6000000.0            USD
2              Tempe    AZ   1-Jan-08   25000000.0            USD
3         Scottsdale    AZ   1-Jan-08      50000.0            USD
4            Phoenix    AZ   1-Feb-08    3000000.0            USD
5            Gilbert    AZ   1-Oct-07    9000000.0            USD
6         Scottsdale    AZ   1-Jan-08     250000.0            USD
7         Scottsdale    AZ   1-Oct-06     140000.0            USD
8         Scottsdale    AZ  25-Jan-08     233750.0            USD
9      San Francisco    CA   1-Dec-06    8500000.0            USD
10     San Francisco    CA   1-Oct-05    2800000.0            USD
11         Palo Alto    CA   1-Sep-04     500000.0            USD
12         Palo Alto    CA   1-May-05   12700000.0            USD
13         Palo Alto    CA   1-Apr-06   27500000.0            USD
14         Palo Alto    CA   1-Oct-07  300000000.0            USD
15         Palo Alto    CA   1-Mar-08   40000000.0            USD
16         Palo Alto    CA  15-Jan-08   15000000.0            USD
17         Palo Alto    CA   1-May-08  100000000.0            USD
18         Palo Alto    CA   1-May-06   10500000.0            USD
19         Palo Alto    CA   1-Mar-05    3000000.0            USD
20         Palo Alto    CA   1-Dec-06     800000.0            USD
21    West Hollywood    CA   1-Jan-07    1500000.0            USD
22    West Hollywood    CA   1-Mar-07   10000000.0            USD
23     San Francisco    CA   1-Jul-07    5400000.0            USD
24     San Francisco    CA   1-May-08   15000000.0            USD
25     San Francisco    CA   1-Dec-05    1500000.0            USD
26        Menlo Park    CA   1-May-07    6300000.0            USD
27        Menlo Park    CA  16-Mar-08    6500000.0            USD
28     San Francisco    CA   1-Jun-06      12000.0            USD
29     San Francisco    CA   1-Jan-07      40000.0            USD
...              ...   ...        ...          ...            ...
1430        Bellevue    WA   1-Dec-07    1000000.0            USD
1431         Seattle    WA   1-Dec-06    1650000.0            USD
1432         Seattle    WA   1-Aug-07    8000000.0            USD
1433        Bellevue    WA   1-Jan-08    6000000.0            USD
1434         Seattle    WA   1-Jan-08    6500000.0            USD
1435         Seattle    WA   1-Aug-06    1400000.0            USD
1436         Seattle    WA   1-Sep-05    1200000.0            USD
1437         Seattle    WA   1-Dec-07     500000.0            USD
1438        Bellevue    WA   1-Jan-08    1200000.0            USD
1439        Bellevue    WA   1-Jan-07    1000000.0            USD
1440        Bellevue    WA   1-Feb-08     850000.0            USD
1441         Seattle    WA   1-Feb-07    1000000.0            USD
1442         Seattle    WA   1-Aug-05   45000000.0            USD
1443         Seattle    WA  19-Dec-05   24000000.0            USD
1444        Kirkland    WA  25-Oct-06    3000000.0            USD
1445         Seattle    WA  29-Jun-07    3000000.0            USD
1446         Seattle    WA   1-Feb-07    9800000.0            USD
1447         Seattle    WA  11-Jun-08   10000000.0            USD
1448         Seattle    WA   1-Mar-08    2250000.0            USD
1449             NaN    WA  24-Apr-08     450000.0            USD
1450       Kennewick    WA  22-Apr-08   57000000.0            USD
1451       Kennewick    WA   1-Jun-07    9500000.0            USD
1452         Seattle    WA  16-Oct-05    7000000.0            USD
1453         Seattle    WA  11-Jul-07    3000000.0            USD
1454         Seattle    WA   1-Jun-08    8000000.0            USD
1455         Seattle    WA   1-Jun-07    2000000.0            USD
1456        Bellevue    WA   8-Jul-08    1200000.0            USD
1457         Bothell    WA   1-Jan-01   20500000.0            USD
1458         Seattle    WA  30-Oct-07    9500000.0            USD
1459         Seattle    WA  20-May-08   10500000.0            USD

          round123
0                b
1                a
2                c
3             seed
4                a
5                a
6             seed
7             seed
8            angel
9                b
10               a
11           angel
12               a
13               b
14               c
15               c
16               c
17      debt_round
18               b
19               a
20           angel
21               a
22               b
23               b
24               c
25            seed
26               a
27               b
28            seed
29           angel
...            ...
1430         angel
1431          seed
1432             a
1433             a
1434             b
1435         angel
1436             a
1437         angel
1438         angel
1439         angel
1440             a
1441             a
1442             a
1443             e
1444             a
1445             a
1446             a
1447             b
1448             a
1449         angel
1450             b
1451             a
1452             b
1453             a
1454             c
1455         angel
1456             a
1457  unattributed
1458             a
1459             b

[1460 rows x 10 columns]>

In [8]:
df.groupby("city").raisedAmt.sum().reset_index().sort_values("raisedAmt", ascending=False)

                city     raisedAmt
148    San Francisco  1.559159e+09
120        Palo Alto  1.306915e+09
98     Mountain View  9.042610e+08
106         New York  7.308900e+08
151        San Mateo  7.120500e+08
157     Santa Monica  6.159000e+08
83       Los Angeles  6.135950e+08
161          Seattle  5.736900e+08
29         Cambridge  4.200500e+08
150         San Jose  4.161300e+08
136     Redwood City  3.680500e+08
141        Rockville  3.299000e+08
121         Pasadena  2.926000e+08
171        Sunnyvale  2.718200e+08
147        San Diego  2.192700e+08
90        Menlo Park  2.178300e+08
114          Norwalk  2.145000e+08
21            Boston  1.911800e+08
13            Austin  1.831500e+08
156      Santa Clara  1.695380e+08
146       San Carlos  1.455000e+08
43         Cupertino  1.313900e+08
158        Sausalito  1.185000e+08
30          Campbell  1.155000e+08
24          Brisbane  1.146000e+08
15          Bellevue  1.121400e+08
64           Ir vine  1.100000e+08
180        Watertown  1.010000e+08
6      American Fork  9.510000e+07
177          Waltham  9.390000e+07
..               ...           ...
191         Woodside  1.000000e+06
66            Ithaca  7.500000e+05
35        Centennial  7.500000e+05
73          La Jolla  6.820000e+05
160       Scottsdale  6.737500e+05
140        Richfield  6.000000e+05
57       Grand Forks  5.700000e+05
132       Providence  5.000000e+05
116          Oakmont  4.000000e+05
103        New Haven  3.750000e+05
76          Leesburg  3.500000e+05
187         Westport  3.500000e+05
14         Baltimore  3.500000e+05
111    North Andover  3.400000e+05
11           Astoria  3.000000e+05
104       New London  2.500000e+05
5          Allentown  2.500000e+05
44            Dallas  2.500000e+05
179        Washinton  2.500000e+05
26           Burbank  2.500000e+05
31          Carlsbad  2.000000e+05
112  North Brunswick  2.000000e+05
34              Cary  2.000000e+05
139       Richardson  1.250000e+05
172            Tampa  1.180000e+05
77              Lehi  8.000000e+04
58            Hamden  7.000000e+04
122        Patchogue  3.000000e+04
105      New Orleans  2.500000e+04
68         Kennebunk  2.000000e+04

[192 rows x 2 columns]

In [9]:
df.round

<bound method DataFrame.round of                permalink              company  numEmps   category  \
0               lifelock             LifeLock      NaN        web
1               lifelock             LifeLock      NaN        web
2               lifelock             LifeLock      NaN        web
3            mycityfaces          MyCityFaces      7.0        web
4               flypaper             Flypaper      NaN        web
5           infusionsoft         Infusionsoft    105.0   software
6                  gauto                gAuto      4.0        web
7         chosenlist-com       ChosenList.com      5.0        web
8         chosenlist-com       ChosenList.com      5.0        web
9                   digg                 Digg     60.0        web
10                  digg                 Digg     60.0        web
11              facebook             Facebook    450.0        web
12              facebook             Facebook    450.0        web
13              facebook             Facebook    450.0        web
14              facebook             Facebook    450.0        web
15              facebook             Facebook    450.0        web
16              facebook             Facebook    450.0        web
17              facebook             Facebook    450.0        web
18           photobucket          Photobucket     60.0        web
19           photobucket          Photobucket     60.0        web
20             omnidrive            Omnidrive      NaN        web
21                  geni                 Geni     18.0        web
22                  geni                 Geni     18.0        web
23               twitter              Twitter     17.0        web
24               twitter              Twitter     17.0        web
25           stumbleupon          StumbleUpon      NaN        web
26                gizmoz               Gizmoz      NaN        web
27                gizmoz               Gizmoz      NaN        web
28                scribd               Scribd     14.0        web
29                scribd               Scribd     14.0        web
...                  ...                  ...      ...        ...
1430            fyreball             Fyreball      NaN        web
1431      delve-networks       Delve Networks      NaN        web
1432      delve-networks       Delve Networks      NaN        web
1433           livemocha            LiveMocha      NaN        web
1434  mercentcorporation  Mercent Corporation     50.0        web
1435           cleverset            CleverSet      NaN        web
1436           cleverset            CleverSet      NaN        web
1437           cleverset            CleverSet      NaN        web
1438       liquidplanner        LiquidPlanner     11.0        web
1439             limeade              Limeade     10.0        web
1440               yodio                Yodio      4.0        web
1441         tastemakers          Tastemakers     11.0        web
1442      whitepages-com       WhitePages.com    125.0        web
1443      revenuescience       RevenueScience      NaN        web
1444            gotvoice             GotVoice     15.0     mobile
1445   cardomain-network    CarDomain Network     50.0        web
1446               mpire                mpire      NaN        web
1447               mpire                mpire      NaN        web
1448         teachstreet          TeachStreet      8.0        web
1449            estately             Estately      NaN        web
1450             infinia              Infinia      NaN  cleantech
1451             infinia              Infinia      NaN  cleantech
1452           m-metrics            M:Metrics      NaN        web
1453                cozi                 Cozi     26.0   software
1454                cozi                 Cozi     26.0   software
1455             trusera              Trusera     15.0        web
1456          alerts-com           Alerts.com      NaN        web
1457               myrio                Myrio     75.0   software
1458       grid-networks        Grid Networks      NaN        web
1459       grid-networks        Grid Networks      NaN        web

                city state fundedDate    raisedAmt raisedCurrency  \
0              Tempe    AZ   1-May-07    6850000.0            USD
1              Tempe    AZ   1-Oct-06    6000000.0            USD
2              Tempe    AZ   1-Jan-08   25000000.0            USD
3         Scottsdale    AZ   1-Jan-08      50000.0            USD
4            Phoenix    AZ   1-Feb-08    3000000.0            USD
5            Gilbert    AZ   1-Oct-07    9000000.0            USD
6         Scottsdale    AZ   1-Jan-08     250000.0            USD
7         Scottsdale    AZ   1-Oct-06     140000.0            USD
8         Scottsdale    AZ  25-Jan-08     233750.0            USD
9      San Francisco    CA   1-Dec-06    8500000.0            USD
10     San Francisco    CA   1-Oct-05    2800000.0            USD
11         Palo Alto    CA   1-Sep-04     500000.0            USD
12         Palo Alto    CA   1-May-05   12700000.0            USD
13         Palo Alto    CA   1-Apr-06   27500000.0            USD
14         Palo Alto    CA   1-Oct-07  300000000.0            USD
15         Palo Alto    CA   1-Mar-08   40000000.0            USD
16         Palo Alto    CA  15-Jan-08   15000000.0            USD
17         Palo Alto    CA   1-May-08  100000000.0            USD
18         Palo Alto    CA   1-May-06   10500000.0            USD
19         Palo Alto    CA   1-Mar-05    3000000.0            USD
20         Palo Alto    CA   1-Dec-06     800000.0            USD
21    West Hollywood    CA   1-Jan-07    1500000.0            USD
22    West Hollywood    CA   1-Mar-07   10000000.0            USD
23     San Francisco    CA   1-Jul-07    5400000.0            USD
24     San Francisco    CA   1-May-08   15000000.0            USD
25     San Francisco    CA   1-Dec-05    1500000.0            USD
26        Menlo Park    CA   1-May-07    6300000.0            USD
27        Menlo Park    CA  16-Mar-08    6500000.0            USD
28     San Francisco    CA   1-Jun-06      12000.0            USD
29     San Francisco    CA   1-Jan-07      40000.0            USD
...              ...   ...        ...          ...            ...
1430        Bellevue    WA   1-Dec-07    1000000.0            USD
1431         Seattle    WA   1-Dec-06    1650000.0            USD
1432         Seattle    WA   1-Aug-07    8000000.0            USD
1433        Bellevue    WA   1-Jan-08    6000000.0            USD
1434         Seattle    WA   1-Jan-08    6500000.0            USD
1435         Seattle    WA   1-Aug-06    1400000.0            USD
1436         Seattle    WA   1-Sep-05    1200000.0            USD
1437         Seattle    WA   1-Dec-07     500000.0            USD
1438        Bellevue    WA   1-Jan-08    1200000.0            USD
1439        Bellevue    WA   1-Jan-07    1000000.0            USD
1440        Bellevue    WA   1-Feb-08     850000.0            USD
1441         Seattle    WA   1-Feb-07    1000000.0            USD
1442         Seattle    WA   1-Aug-05   45000000.0            USD
1443         Seattle    WA  19-Dec-05   24000000.0            USD
1444        Kirkland    WA  25-Oct-06    3000000.0            USD
1445         Seattle    WA  29-Jun-07    3000000.0            USD
1446         Seattle    WA   1-Feb-07    9800000.0            USD
1447         Seattle    WA  11-Jun-08   10000000.0            USD
1448         Seattle    WA   1-Mar-08    2250000.0            USD
1449             NaN    WA  24-Apr-08     450000.0            USD
1450       Kennewick    WA  22-Apr-08   57000000.0            USD
1451       Kennewick    WA   1-Jun-07    9500000.0            USD
1452         Seattle    WA  16-Oct-05    7000000.0            USD
1453         Seattle    WA  11-Jul-07    3000000.0            USD
1454         Seattle    WA   1-Jun-08    8000000.0            USD
1455         Seattle    WA   1-Jun-07    2000000.0            USD
1456        Bellevue    WA   8-Jul-08    1200000.0            USD
1457         Bothell    WA   1-Jan-01   20500000.0            USD
1458         Seattle    WA  30-Oct-07    9500000.0            USD
1459         Seattle    WA  20-May-08   10500000.0            USD

          round123
0                b
1                a
2                c
3             seed
4                a
5                a
6             seed
7             seed
8            angel
9                b
10               a
11           angel
12               a
13               b
14               c
15               c
16               c
17      debt_round
18               b
19               a
20           angel
21               a
22               b
23               b
24               c
25            seed
26               a
27               b
28            seed
29           angel
...            ...
1430         angel
1431          seed
1432             a
1433             a
1434             b
1435         angel
1436             a
1437         angel
1438         angel
1439         angel
1440             a
1441             a
1442             a
1443             e
1444             a
1445             a
1446             a
1447             b
1448             a
1449         angel
1450             b
1451             a
1452             b
1453             a
1454             c
1455         angel
1456             a
1457  unattributed
1458             a
1459             b

[1460 rows x 10 columns]>

In [10]:
df.round.value_counts()

AttributeError: 'function' object has no attribute 'value_counts'

In [ ]:
df.round.value_counts

In [ ]:
df.category.value_counts()

In [ ]:
df.raisedCurrency

In [ ]:
df.round.value_counts()

In [ ]:
df[df.columns[-1]]

In [ ]:
df.info()

In [ ]:
df.round123.value_counts()

In [ ]:
df.round123.value_counts().reset_index()

In [ ]:
df.city.value_counts.reset_index()

In [ ]:
df.city.value_counts().reset_index()

In [ ]:
df.shape

In [ ]:
df.round123 == "angel"

In [ ]:
df[df.round123 == "angel"]

In [ ]:
 filtered_by_angel=df[df.round123 == "angel"]

In [ ]:
formerge=pd.read_csv("http://www.fema.gov/api/open/v1/DisasterDeclarationsSummaries.csv")

In [ ]:
twomerged=pd.merge(filtered_by_angel,formerge,on="state")

In [ ]:
twomerged.info()

In [ ]:
twomerged.raisedAmt.sum()

In [ ]:
twomerged.groupby("round123")